screener_urls:
  RT Range Breakout with Volume: "https://chartink.com/screener/rt-range-breakout-with-volume"
  RT Fib 0.7 to 0.88 Zone: "https://chartink.com/screener/rt-fib-o-7-to-0-88-zone"
  RT Daily Contraction: "https://chartink.com/screener/rt-daily-contraction"
  RT Master Resistance Breakout Screener: "https://chartink.com/screener/rt-master-resistance-breakout-screener"
  Premium 7.1: "https://chartink.com/screener/premium-7-1"
  RT COP Strategy: "https://chartink.com/screener/rt-cop-strategy"
  Premium 3 for Momentum: "https://chartink.com/screener/premium-3-for-momentum"
  RT 8EMA Sniper Entry 2: "https://chartink.com/screener/rt-8ema-sniper-entry-2"
  RT SIDEWAY BREAKOUT: "https://chartink.com/screener/rt-sideways-breakout-after-a-strong-uptrend"
  GEM SWING: "https://chartink.com/screener/gem-swing-strategy"
  ENTRY BELOW MA: "https://chartink.com/screener/rt-how-to-take-entry-below-moving-average-2"
  SNIPER IN PROCESS: "https://chartink.com/screener/adaw-2"
  EMA 200: "https://chartink.com/screener/rt-ema-200-support-on-daily"
  DARVAS: "https://chartink.com/screener/rt-darvas-box-breakout-stocks"
  VCP: "https://chartink.com/screener/copy-vcp-32713"
  RT-52W AWAY: "https://chartink.com/screener/rt-15-20-and-25-away-from-52-week-highs"
  RT 52W BREAKOUT: "https://chartink.com/screener/rt-52-week-breakout-setups"
  RT MULTIYEAR RETEST: "https://chartink.com/screener/final-countdown-15"
  RT COP DAILY: "https://chartink.com/screener/rt-661"
  RT IPO SCREENER: "https://chartink.com/screener/rt-ipo-stocks-screener"
  RT SHORT TO MID RANGE BREAKOUT: "https://chartink.com/screener/copy-copy-swing-high-breakout-47"
  RT MAJOR SUPPORT: "https://chartink.com/screener/rt-stocks-at-major-support"
  RSI in all TF > 65: "https://chartink.com/screener/rsi-in-all-tf-above-65"
  RT HIGH STRENGTH : "https://chartink.com/screener/rt-high-strength-stocks"
  RT RSI > 85: "https://chartink.com/screener/rt-rsi-crossing-above-85-in-monthly"
